from __future__ import annotations

import math
import random
from datetime import date, datetime, timedelta
from typing import List, Optional

from persistence.database import session_scope
from persistence.models.room import Room
from persistence.models.patient import Patient
from persistence.models.room_assignment import RoomAssignment

from simulation_batch.config import (
    PATIENT_COUNT,
    DAYS,
    START_DATE,
)

from simulation_batch.generators.patients import generate_patients
from simulation_batch.generators.name_gen import generate_name
from simulation_batch.generators.age_height_weight_gen import age_height_weight_generator

# Runtime (not DB) device/sensor objects
from ble import Device as BLEDevice, Sensor as BLESensor


# -------------------------
# Helpers
# -------------------------

def _ensure_datetime_midnight(d: date | datetime) -> datetime:
    if isinstance(d, date) and not isinstance(d, datetime):
        return datetime.combine(d, datetime.min.time())
    return d.replace(hour=0, minute=0, second=0, microsecond=0)


def _random_mac(rng: random.Random) -> str:
    return "02:00:00:%02x:%02x:%02x" % (
        rng.randint(0, 255),
        rng.randint(0, 255),
        rng.randint(0, 255),
    )


def _unit_for(st: str) -> str:
    return {
        "temperature": "°C",
        "humidity": "%",
        "co2": "ppm",
        "light": "lux",
        "sound": "dB",
    }.get(st, "")


# -------------------------
# Seeding
# -------------------------

def seed_simulated_world(
    *,
    seed: int = 42,
    patient_count: int = PATIENT_COUNT,
    days: int = DAYS,
    start_date: date | datetime = START_DATE,
    include_speaker: bool = True,
) -> List[BLEDevice]:
    """
    Seeds DB:
      - Rooms (dynamic count, created as needed)
      - Patients
      - RoomAssignments (patients placed into rooms across [start_date, start_date+days])

    Returns runtime devices (BLEDevice list) for:
      - main sensor device per room (temp, humidity, co2, light, sound)
      - toilet sensor device per room (temp)
      - ventilation device per room (no sensors)
      - speaker device per room (optional, no sensors)
      - toilet heater device per room (no sensors)
      - toilet light device per room (no sensors)

    NOTE:
      - ComfortPreference is NOT seeded here anymore.
        That is generated by simulation_batch/comfort_generator.py during the run.
      - After this, call seed_devices_and_sensors(devices) to insert devices/sensors into DB.
    """
    rng = random.Random(seed)
    start_dt = _ensure_datetime_midnight(start_date)

    main_sensor_types = ("temperature", "humidity", "co2", "light", "sound")
    toilet_sensor_types = ("temperature",)

    # --------- Build patients ----------
    patients: list[Patient] = []
    stay_days_list: list[int] = []

    for p in generate_patients(patient_count):
        age_hw = age_height_weight_generator()
        patient = Patient(
            age=age_hw["age"],
            name=generate_name(),
            current_diagnosis=p["diagnosis"],
            ethnicity=p["ethnicity"],
            gender=rng.choice(["Male", "Female"]),
            height=age_hw["height"],
            weight=age_hw["weight"],
        )

        stay_days = rng.randint(5, 20)
        if hasattr(patient, "stay_days"):
            patient.stay_days = stay_days

        patients.append(patient)
        stay_days_list.append(stay_days)

    ble_devices: List[BLEDevice] = []

    with session_scope() as session:
        # insert patients first so they get IDs
        for patient in patients:
            session.add(patient)
        session.flush()

        # --------- Dynamic room allocation ----------
        # We create rooms as needed. Each room hosts sequential stays until we exceed `days`,
        # then we open a new room.
        rooms: list[Room] = []
        current_room: Optional[Room] = None
        current_offset_days = 0
        room_index = 0

        for patient, stay in zip(patients, stay_days_list):
            # If no room yet or patient doesn't fit in remaining horizon for this room, open new room
            if current_room is None or (current_offset_days + stay > days):
                room_index += 1
                current_offset_days = 0

                current_room = Room(room_number=100 + room_index)
                session.add(current_room)
                session.flush()
                rooms.append(current_room)

            # admission & release within the room timeline
            admission = start_dt + timedelta(days=current_offset_days)
            release = admission + timedelta(days=stay)

            if hasattr(patient, "admission_date"):
                patient.admission_date = admission
            if hasattr(patient, "release_date"):
                patient.release_date = release

            session.add(
                RoomAssignment(
                    patient_id=patient.patient_id,
                    room_id=current_room.room_id,
                    start_time=admission,
                    end_time=release,
                )
            )

            current_offset_days += stay

        session.flush()

        # --------- Create runtime devices per room ----------
        for room in rooms:
            # MAIN sensor device
            mac_main = _random_mac(rng)
            dev_main = BLEDevice(mac_address=mac_main, label=f"Room {room.room_number} Main Sensor")
            dev_main.room_id = room.room_id
            dev_main.device_type = "sensor"
            dev_main.location = "main"

            for st in main_sensor_types:
                uuid = f"{mac_main}-{st}"
                dev_main.add_sensor(BLESensor(uuid=uuid, sensor_type=st, unit=_unit_for(st), parser=lambda b: None))
            ble_devices.append(dev_main)

            # TOILET sensor device
            mac_toilet = _random_mac(rng)
            dev_toilet = BLEDevice(mac_address=mac_toilet, label=f"Room {room.room_number} Toilet Sensor")
            dev_toilet.room_id = room.room_id
            dev_toilet.device_type = "sensor"
            dev_toilet.location = "toilet"

            for st in toilet_sensor_types:
                uuid = f"{mac_toilet}-{st}"
                dev_toilet.add_sensor(BLESensor(uuid=uuid, sensor_type=st, unit=_unit_for(st), parser=lambda b: None))
            ble_devices.append(dev_toilet)

            # Ventilation device (actuator, no sensors)
            vent = BLEDevice(mac_address=None, label=f"Room {room.room_number} Ventilation")
            vent.room_id = room.room_id
            vent.device_type = "ventilation"
            vent.location = "main"
            ble_devices.append(vent)

            # Speaker device (actuator, no sensors)
            if include_speaker:
                spk = BLEDevice(mac_address=None, label=f"Room {room.room_number} Speaker")
                spk.room_id = room.room_id
                spk.device_type = "speaker"
                spk.location = "main"
                ble_devices.append(spk)

            # Toilet heater device (actuator, no sensors)
            th = BLEDevice(mac_address=None, label=f"Room {room.room_number} Toilet Heater")
            th.room_id = room.room_id
            th.device_type = "toilet_heater"
            th.location = "toilet"
            ble_devices.append(th)

            # Toilet light device (actuator, no sensors)
            tl = BLEDevice(mac_address=None, label=f"Room {room.room_number} Toilet Light")
            tl.room_id = room.room_id
            tl.device_type = "toilet_light"
            tl.location = "toilet"
            ble_devices.append(tl)

    return ble_devices
